---
title: "ஜிம்மி "
description: |
  This is dedicated to one of my best buddies in my childhood. My Jimmy
author:
  - name: Geetha Soundararajan
    url: {}
date: 04-25-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

வாலைக் குழைத்து வரும் நாய்தான் அது மனிதருக்கு தோழனடி பாப்பா என்ற பாரதியின் பாடலை மெய்ப்பித்து பழகியவன் தான் எனது அழகு ஜிம்மி.\
விடுமுறையில் தாத்தா வீடு சென்று திரும்பி வீட்டுக்கு வந்தால் கால்களை சுற்றி சுற்றி அழகான வெளிர் ப்ரவுன் நிறத்தில் குட்டி நாய்.

அம்மாஆஆ என்று ஓடி நாற்காலி மேல் ஏறிக் கொண்டேன். பயப்படாதே ஒன்றும் செய்யாது என்று அம்மா சமாதானம் செய்தார். இருந்தும் பயம் விலகாமல் நாற்காலி, மேஜை , கட்டில் என்று ஏறி நின்று அம்மா தண்ணி வேணும் பிஸ்கட் வேணும் என்று நானும் தங்கையும் ஒரே லூட்டி.

அதுவும் மேலே தாவி தாவி நாற்காலி மேல் ஏறக் கற்றுக்கொண்டுவிட்டது. பழகப் பழக எங்களுக்கு பயம் போய் நல்ல நண்பனாகி விட்டது. ஜிம்மி என்று பெயர் வைத்தோம். எங்கு சென்றாலும் உடன் வரும். அப்பா ஆபீஸ் செல்லும்போது கூடவே சென்று வரும்.\
சிறிய குட்டியானதால் பால் மட்டுமே உணவு. பாலைக் குடித்து புசுபுசுவென்று புஷ்டியாக அழகாக வளர்ந்துவிட்டது.

ஒருநாள் நாங்கள் சாப்பிடும்பொழுது அருகில் வந்து விட்டது. அம்மாவோ தட்டில் வாய் வைத்துவிடும் என்று பயந்து போ அந்தப்பக்கம் என்று கைகளால் தள்ளிவிட திண்ணையிலிருந்து கீழே விழுந்துவிட்டது. வீல் வீல் என ஒரே சத்தம். எல்லோரும் எழுந்து வந்து பார்த்தால்  காலில் 
 அடிபட்டு வலி தாங்காமல் கத்தியது. உடனே அம்மா மஞ்சள் அரைத்து பற்று போட்டு கட்டி விட்டார்கள்.

இரண்டு நாளில் குணமாகி விட்டது. அதுமுதல் நாங்கள் சாப்பிடும்போது அருகில் வருவதில்லை. அதற்கு என உள்ள தட்டில் உணவு வைக்கும்போதுதான் சாப்பிடும். எனக்கு ஜிம்மியை மிகவும் பிடிக்கும். அதுவும் நான் ஜிம்மி என்று கூப்பிட்டதும் வாலைக் குழைத்துக்கொண்டு ஆட்டி நம்மிடம் அதன் அன்பைத் தெரிவிக்கும் பண்பு மிகவும் அழகானது.

அப்பாவின் வேலை நிமித்தம் வேறு ஊருக்கு வரும்பொழுது ஜிம்மியை அழைத்து வர முடியவில்லை. பக்கத்து வீட்டில் விட்டு வந்தோம். கடிதம் மூலம் ஜிம்மியின் நலம் விசாரிப்போம். எங்கள் வீட்டுக்குப் போய் பார்க்குமாம். கொஞ்ச நாள் சாப்பிடாமல் கூட இருந்ததாம். எங்களுக்கும் ஜிம்மியைப் பிரிந்ததில் வருத்தம்தான், அதனால் அதன்பின் நாங்கள் வீட்டில் நாய் வளர்ப்பதில்லை.

பாசம் வைத்து பிரிவு வந்தால் ஜிம்மியாக இருந்தாலும் மனம் வலிக்கத்தான் செய்கிறது.

*Geetha Soundararajan*
