---
title: "கதை நேரம்   "
description: |
  மார்கழி
author:
  - name: Geetha Soundararajan
    url: {}
date: 04-17-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

காலை  5.30 மணி; தூக்கம் லேசாக கலைந்து எழுந்து வந்து வாசலில் பார்த்தால் அம்மா வாசல் தெளித்துப் பெருக்கி வாசல் நிறைத்து பெரிய கோலம் போட்டிருப்பதைப் பார்த்ததும் மனம் மகிழ்ச்சி கொண்டது. இத்தனை நேரம் தூங்கியதை நினைத்து வெட்கமாய் இருந்தது. நான் கலர் போடுகிறேன் என்று குஷியாக கலர் போட்டு முடிவதற்குள் அம்மா கமகமக்கும் வாசனையோடு சூடான காபியுடன் வந்தார். திண்ணையிலேயே ஊஞ்சலில் அமர்ந்து அப்பா நான் எல்லாரும் காபி குடித்தபடியே கோலத்தை ரசித்தோம்.  


எப்படி தினமும் நேரம் தவறாமல் அதிகாலை எழுந்து சிரத்தையாக இதையெல்லாம் செய்ய அம்மாவால் முடிகிறது நாமும் அம்மா போல் சுறுசுறுப்பாக இருக்க வேண்டும் என்ற எண்ணம் விதையாய் விழுந்தது.   அதிகாலை கூவின பூங்குயில் கூவின கோழி என்ற மாணிக்கவாசகர் திருப்பள்ளி எழுச்சியுடன் பஜனை கோஷ்டியினர் பாடிய பாடல் காதில் விழுந்ததும், 
ஏய் ஜெயா அத்தை என்ன கோலம் போட்டாங்க வா போயி பாக்கலாம் என்று ஒரு ரவுண்டு. ஓ21   புள்ளி  சிக்கு கோலம். மீனா வீட்ல திராட்சை கோலம். காமாட்சி இப்பதான் புள்ளி வைக்கிறா இப்படியாக மார்கழியில் காலை நேர புத்துணர்ச்சி   


வாடி கொழந்தே அம்மா நன்னாருக்காளா ஊஞ்சல்ல உக்காந்து பாடிண்டிரு வந்துடறேன் horlicks   குடிச்சாச்சா உக்காந்துக்கோடி கொழந்தே அன்பாக ஆசையுடன் உபசரிக்கும் குருக்கள் வீட்டு மாமி. நாகப்பழம் வாங்கினாரே நந்தகோபாலனும் நவநீத பாடல் நின்றது. ஏண்டி பாட்ட நிறுத்திட்ட, பாடு மறுபடி அமைதி உள்ளிருந்து மாமி எட்டிப்பார்க்க ஊஞ்சலில் பானு அமைதியாய் இருக்க, எதிரில் மாமி மகன் செல்லப்பா, " ம் 9   -ஆம் வாய்ப்பாடு சொல்லு"என்றபடி நிற்க, ஏண்டா பாடிண்டு இருக்கவளை வாய்ப்பாடு சொல்லச் சொல்லி மிரட்டற. உன் ட்யூஷன்   க்கு  வரச்சே சொல்ல சொல்லு, சொல்லுவா குழந்தையை மிரட்டாதடா பயந்துட்டா.       


" ம் ம் பாட்டெல்லாம் நன்னாத்தான் பாடறா வாய்ப்பாடுதான் வர மாட்டேங்குது" ,   "எல்லாம் வரும் போடா அந்தண்ட" என்றபடி மாமி மகனை விரட்டினாள். அப்போதுதான் டீச்சர் ட்ரைனிங் முடித்து வேலைக்காக காத்திருக்கும் எதிர்கால வாத்தியார். அவனிடம்தான் பானு கணக்கு பாடத்திற்கு ட்யூஷன் படிக்கிறாள். அதனால் தான் இந்த மிரட்டல்.    

வாய்ப்பாடெல்லாம் அப்புறம் சொல்லிக்கலாம் நீ இப்ப பாட்ட பாடி முடி என்று மாமியும் உடன் பாட இருவரும் பாடி முடித்தார்கள். மாமி தோட்டத்தில் பறித்த பூக்களைத் தொடுத்து சுவாமிக்கு போட்டு விட்டு சிறிது பானுவிடமும் கொடுத்தாள். Thanks      மாமி என்றபடி வாங்கி கொண்டாள்.      

மூன்றாம் வகுப்பு பானுவும் மாமியும் நல்ல தோழிகள் மாமிக்கு பெண் குழந்தைகள் கிடையாது, எனவே பானு மீது மாமிக்கு வாஞ்சை அதிகம். பானு அந்த ஊர் கோயில் நிர்வாக அதிகாரியின் மகள். கோயிலில் அர்ச்சனை செய்யும் குருக்கள் மனைவிதான் பானுவைக் கொண்டாடும் மாமி. தினமும் மாலை வேளையில் பானுவும் மாமி வீட்டுக்கு வந்து செல்வாள். இருவரும் ஆஞ்சநேயர் கோயிலுக்கு செல்வார்கள். மாமி நிறைய ஸ்லோகங்கள் சொல்லிக்கொடுப்பார். சாயி பஜன் பாடுவார்கள்.   

பானு வீட்டுக்கு கிளம்பும்போது டீ கொழந்தே அந்த 9    -  ஆம் வாய்ப்பாட்டை படிச்சுட்டு வந்துடுடி இல்லைனா செல்லப்பா நாளைக்கும் முறைப்பான் என்றதும் சரி மாமி என்று கூறி இருவரும் சிரித்தபடியே பானு விடைபெற்றாள். 




