---
title: "கதை நேரம் 2"
description: |
   All in all கல்யாணி 
author:
  - name: Geetha Soundararajan
    url: {}
date: 05-05-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

ஏ பொண்ணு யார் நீ ஏன் இங்கயே நிக்கிற என்றதற்கு அவள், " எங்க அம்மா இங்க வீட்டு வேலை செய்யுறாங்க, அதுனால வந்தேன்." , சரி அதுக்கு ஏன் வாசல்லயே நிக்கிற, உள்ள வா என்றதும் தயங்கியவாறே வந்தாள்.

உன் பேர் என்ன. கல்யாணி என்றாள். மெலிந்த தேகத்தோடு தலையில் எண்ணை வைத்து அழுந்த பின்னிய ஒற்றை சடையில் பாவாடை சட்டை தாவணி அணிந்து 15 வயது இருக்கும்.

அம்மா வேலை முடித்து வருவாங்க உட்கார்ந்து கொள் என்று சொல்ல, அங்கு வந்த 2 வயது அக்கா பையனுக்கு நடைவண்டி ஓட்ட உதவினாள்.

இவ்வாறு அறிமுகமான கல்யாணி, தினமும் வீட்டிற்கு வர ஆரம்பித்தாள். ஒருநாள் "அம்மா ஊருக்கு போனவர் வரல நானே வீட்டு வேலைகளில் உதவுகிறேன்" என்று எல்லா வேலைகளிலும் அம்மாவுக்கு உதவி செய்தாள்.

காய் நறுக்குவது, வீடு பெருக்கி துடைப்பது, துணி துவைப்பது, அடுக்களையில் கூட மாட இருப்பது என்று பம்பரமாய் வேலை செய்தாள். அம்மாவுக்கு மிகவும் பிடித்துவிட்டது. கல்யாணி டிபன் எடுத்து டேபிளில் வை தண்ணீர் எடுத்து வா என்று சொன்னதும் மின்னலாய் செயல்பட்டாள்.

கல்யாணி பாபுவுக்கு இட்லி ஊட்டிவிடு என்றதும், பாபு 2 இட்லி சாப்பிட்டுச்சு அக்கா என்றாள் ஏய் நாங்க ஊட்டி விட்டால் சாப்பிடறதே இல்ல நீ கொடுத்தா 2 இட்லி சாப்பிட்டானா ஏய் நீ சாப்பிட்டியா இல்ல காக்காவுக்கு போட்டியா என்று சுவையான கலாட்டாக்களுடன் நகர்ந்தன நாட்கள்.

கல்யாணி துண்டு கொண்டு வா, இது அப்பா, இதோ வரேங்க அய்யா என்று ஓடுவாள். கல்யாணி கறிவேப்பிலை பறித்து வா சீக்கிரம் சட்னி தாளிக்கணும் இது அம்மா. இந்தாங்க அம்மா என்று கறிவேப்பிலையுடன் வருவாள்.

பாபுவுக்கு டிரஸ் மாத்திவிடு கல்யாணி இது அக்கா. சரி அக்கா என்பாள். கல்யாணி நான் இன்னும் காபி குடிக்கல. அண்ணனுக்கு கொடுக்கும்போது எனக்கும் மறந்துடாதடி என்பேன். எனக்குப் பிடித்த கப் அண்ட் சாசரிலும், அவருக்கு க்ளாஸிலும் காபி எடுத்து வருவாள். கல்யாணி எனக்கு நெய் தோசை, முறுகலா வேணும் அப்டியே அதுல ஜீனியும் போட்டு எடுத்து வாடி, இது தங்கை.

கல்யாணி நீ அந்த மிளகாய் சட்னி அரைச்சுடு, அப்போதான் இன்னுமொரு தோசை அதிகமா சாப்பிடலாம் என்று ஆளாளுக்கு கல்யாணி உதவிக்கரம் நீட்டினாள்.

டேபிள்ள வெச்ச நோட்புக் எங்க என்றால், அந்த கபோர்ட்ல இருக்கு என்று எடுத்து தருவாள். எங்கள் வீட்டுப் பெண் போலவே வீட்டில் வளைய வந்தாள். அம்மாவுடன் பழகியதில் எல்லா வேலைகளும் அத்துப்படியாயிற்று.

சுறுசுறுப்பாக இருப்பாள். யார் கூப்பிட்டாலும் உடனே வந்து என்ன வேண்டும் என்று எதிரில் நிற்பாள். யார் எந்த வேலை சொன்னாலும் முகம் கோணாமல் செய்து முடிப்பாள். எதற்கெடுத்தாலும் எல்லாருக்கும் கல்யாணி கல்யாணிதான். கல்யாணி கல்யாணம் ஆகி கணவருடன் சென்று விட்டாள். அவ்வப்போது வந்து செல்வாள். அவளது குழந்தைகளும் எங்களை பெரியம்மா என்று உரிமையுடன் அழைப்பார்கள்.

**கல்யாணி வீட்டு வேலை செய்பவர் மட்டுமல்ல. எங்கள் வீட்டில் அனைவரது நலம் விரும்பும் நல்ல தோழி.**

*Geetha Soundararajan*
